---
apiVersion: v1
kind: Service
metadata:
  name: is-it-monday-backend
  labels:
    app.kubernetes.io/name: is-it-monday-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: is-it-monday
spec:
  selector:
    app.kubernetes.io/name: is-it-monday-backend
  ports:
    - port: 80
      targetPort: http
...
