---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: is-it-monday-ingress
  labels:
    app.kubernetes.io/name: is-it-monday-ingress
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: is-it-monday
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
    - host: is-it-monday.eyanje.net
      http:
        paths:
          - backend:
              service:
                name: is-it-monday-frontend
                port:
                  name: http
            pathType: Prefix
            path: /
    - host: api.is-it-monday.eyanje.net
      http:
        paths:
          - backend:
              service:
                name: is-it-monday-backend
                port:
                  name: http
            pathType: Prefix
            path: /
  tls:
    - hosts:
        - is-it-monday.eyanje.net
        - api.is-it-monday.eyanje.net
      secretName: is-it-monday-ingress
...
